spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cardb
    username: root
    password: Crediti20$
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
